### ISSUE TITLE
Database lock timeout

### ISSUE THREAD

**Issue by fsiddi** [armadillica/flamenco#133]
This happens, don't know why.

```
[Wed May 13 20:16:57.478877 2015] [wsgi:error] [pid 30746] ERROR:application:Internal Error
[Wed May 13 20:16:57.482335 2015] [wsgi:error] [pid 30746] Traceback (most recent call last):
[Wed May 13 20:16:57.482356 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Wed May 13 20:16:57.482401 2015] [wsgi:error] [pid 30746]     rv = self.dispatch_request()
[Wed May 13 20:16:57.482419 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Wed May 13 20:16:57.484171 2015] [wsgi:error] [pid 30746]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed May 13 20:16:57.489614 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 446, in wrapper
[Wed May 13 20:16:57.493649 2015] [wsgi:error] [pid 30746]     resp = resource(*args, **kwargs)
[Wed May 13 20:16:57.504256 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/flask/views.py", line 84, in view
[Wed May 13 20:16:57.504353 2015] [wsgi:error] [pid 30746]     return self.dispatch_request(*args, **kwargs)
[Wed May 13 20:16:57.507290 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 550, in dispatch_request
[Wed May 13 20:16:57.507572 2015] [wsgi:error] [pid 30746]     resp = meth(*args, **kwargs)
[Wed May 13 20:16:57.509579 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/flamenco/server/application/modules/tasks/__init__.py", line 463, in get
[Wed May 13 20:16:57.517517 2015] [wsgi:error] [pid 30746]     for t in tasks:
[Wed May 13 20:16:57.517700 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2441, in __iter__
[Wed May 13 20:16:57.521428 2015] [wsgi:error] [pid 30746]     return self._execute_and_instances(context)
[Wed May 13 20:16:57.521745 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2456, in _execute_and_instances
[Wed May 13 20:16:57.528484 2015] [wsgi:error] [pid 30746]     result = conn.execute(querycontext.statement, self._params)
[Wed May 13 20:16:57.528512 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
[Wed May 13 20:16:57.529857 2015] [wsgi:error] [pid 30746]     return meth(self, multiparams, params)
[Wed May 13 20:16:57.536769 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
[Wed May 13 20:16:57.536786 2015] [wsgi:error] [pid 30746]     return connection._execute_clauseelement(self, multiparams, params)
[Wed May 13 20:16:57.536793 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
[Wed May 13 20:16:57.537110 2015] [wsgi:error] [pid 30746]     compiled_sql, distilled_params
[Wed May 13 20:16:57.537279 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
[Wed May 13 20:16:57.537617 2015] [wsgi:error] [pid 30746]     context)
[Wed May 13 20:16:57.538487 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
[Wed May 13 20:16:57.546314 2015] [wsgi:error] [pid 30746]     exc_info
[Wed May 13 20:16:57.548003 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
[Wed May 13 20:16:57.548022 2015] [wsgi:error] [pid 30746]     reraise(type(exception), exception, tb=exc_tb)
[Wed May 13 20:16:57.550140 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
[Wed May 13 20:16:57.550162 2015] [wsgi:error] [pid 30746]     context)
[Wed May 13 20:16:57.555980 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
[Wed May 13 20:16:57.556551 2015] [wsgi:error] [pid 30746]     cursor.execute(statement, parameters)
[Wed May 13 20:16:57.561976 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
[Wed May 13 20:16:57.564636 2015] [wsgi:error] [pid 30746]     self.errorhandler(self, exc, value)
[Wed May 13 20:16:57.564659 2015] [wsgi:error] [pid 30746]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
[Wed May 13 20:16:57.574901 2015] [wsgi:error] [pid 30746]     raise errorclass, errorvalue
[Wed May 13 20:16:57.574931 2015] [wsgi:error] [pid 30746] OperationalError: (OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction') 'SELECT task.id AS task_id, task.job_id AS task_job_id, task.manager_id AS task_manager_id, task.name AS task_name, task.status AS task_status, task.priority AS task_priority, task.type AS task_type, task.settings AS task_settings, task.log AS task_log, task.activity AS task_activity, task.child_id AS task_child_id, task.parser AS task_parser, task.time_cost AS task_time_cost, task.last_activity AS task_last_activity \\nFROM task \\nWHERE (task.status = %s OR task.status = %s) AND task.manager_id = %s ORDER BY task.priority DESC, task.id ASC FOR UPDATE' ('ready', 'aborted', 3L)
```

**Comment by Eibriel** [comment]
When a Worker ask for a new Task the task table on the Server database is locked until the task is properly assigned. If several workers ask for tasks at the same time the server could not be able to respond to all the requests raising a Timeout. However this should be not a problem, if the worker continue working properly after the connection is closed it will just ask again until the server is able to respond (most probably right after the exception).

**Comment by Eibriel** [comment]
I think I tried to catch that exception without success.

**Comment by fsiddi** [comment]
I've been monitoring this a bit more closely. The server completely hangs when while the table is locked, and so do the workers. I'll look into this myself as it's degrading the job dispatching performance a lot.

**Comment by tofarley** [comment]
Sounds like you are using the MyISAM storage engine. INNODB supports row-level locking and thus would not suffer from this issue. INNODB is now the default storage engine in mysql 5.6.

If you are running mysql prior to version 5.5.5 then your default database engine is MyISAM, and thus the table-level locking.

Ubuntu Utopic ships with mysql-server 5.5.43. RHEL 6 is version 5.1. (Ubuntu vivid and RHEL 7 are both on 5.6).

The simplest fix this problem on mysql 5.5 is to specify INNODB as your storage engine:
https://dev.mysql.com/doc/refman/5.5/en/storage-engine-setting.html

**Comment by fsiddi** [comment]
Thanks! We are (already) using InnoDB.

**Comment by fsiddi** [comment]
We are using a new dispatch system that is meant to prevent threading issues, so we close this for the moment.
