### ISSUE TITLE
Worker crashes when chunk size is less than total number of exported frames.

### ISSUE THREAD

**Issue by tofarley** [armadillica/flamenco#135]
I'm a little gunshy after my last report. I understand that this is beta and some things may not be implemented yet.

In my testing, it seems that whenever I set the "chunk size" in the blender plugin to be anything less than the length of the scene (in frames) that the worker gets to the last frame of the chunk, then tries to execute a cleanup procedure. An exception is thrown when it tries to delete a non-empty directory which crashes the worker and leaves the entire job in a stuck state.

In the example worker output below, the chunk size was set to 5. I have attempted this at least a dozen times using different settings for the chunk size and animation length.

The error message:

```
Saved: /tmp/flamenco-worker/1/output/1/0005.png Time: 00:16.38 (Saving: 00:00.66)


Saving thumbnail_1.png to /tmp/flamenco-worker/thumbnail_1.png
[]

Blender quit

[]
Worker Loop
Registering
Quering for a new task
New Task Found 2, job 1
Traceback (most recent call last):
  File "./manage.py", line 63, in <module>
    manager.run()
  File "/home/tofarley/flamenco/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/tofarley/flamenco/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/tofarley/flamenco/venv/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "./manage.py", line 48, in runserver
    controllers.worker_loop()
  File "/home/tofarley/flamenco/flamenco/worker/application/controllers.py", line 222, in worker_loop
    clean_dir(tmp_folder, task['job_id'])
  File "/home/tofarley/flamenco/flamenco/worker/application/__init__.py", line 18, in clean_dir
    os.rmdir(os.path.join(root, name))
OSError: [Errno 39] Directory not empty: '/tmp/flamenco-worker/1/output'
```

**Comment by Eibriel** [comment]
Hi! can you post the content of the dir '/tmp/flamenco-worker/1/output' ?

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
