### ISSUE TITLE
Timeout Error on list managers or workers

### ISSUE THREAD

**Issue by fsiddi** [armadillica/flamenco#137]
Might be related to #133 
Seems to happen when too many workers are inactive for too long.
```
[Mon May 25 15:07:46.946862 2015] [wsgi:error] [pid 31001] ERROR:application:Internal Error
[Mon May 25 15:07:46.952527 2015] [wsgi:error] [pid 31001] Traceback (most recent call last):
[Mon May 25 15:07:46.967702 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Mon May 25 15:07:46.976952 2015] [wsgi:error] [pid 31001]     rv = self.dispatch_request()
[Mon May 25 15:07:46.980998 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Mon May 25 15:07:46.987777 2015] [wsgi:error] [pid 31001]     return self.view_functions[rule.endpoint](**req.view_args)
[Mon May 25 15:07:46.988834 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 446, in wrapper
[Mon May 25 15:07:47.002297 2015] [wsgi:error] [pid 31001]     resp = resource(*args, **kwargs)
[Mon May 25 15:07:47.002501 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/flask/views.py", line 84, in view
[Mon May 25 15:07:47.013329 2015] [wsgi:error] [pid 31001]     return self.dispatch_request(*args, **kwargs)
[Mon May 25 15:07:47.014158 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 550, in dispatch_request
[Mon May 25 15:07:47.014172 2015] [wsgi:error] [pid 31001]     resp = meth(*args, **kwargs)
[Mon May 25 15:07:47.014177 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/flamenco/server/application/modules/tasks/__init__.py", line 450, in get
[Mon May 25 15:07:47.014223 2015] [wsgi:error] [pid 31001]     manager = Manager.query.filter_by(ip_address=ip_address).first()
[Mon May 25 15:07:47.014380 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2370, in first
[Mon May 25 15:07:47.017340 2015] [wsgi:error] [pid 31001]     ret = list(self[0:1])
[Mon May 25 15:07:47.019358 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2231, in __getitem__
[Mon May 25 15:07:47.021877 2015] [wsgi:error] [pid 31001]     return list(res)
[Mon May 25 15:07:47.024949 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2441, in __iter__
[Mon May 25 15:07:47.024963 2015] [wsgi:error] [pid 31001]     return self._execute_and_instances(context)
[Mon May 25 15:07:47.032628 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2454, in _execute_and_instances
[Mon May 25 15:07:47.036077 2015] [wsgi:error] [pid 31001]     close_with_result=True)
[Mon May 25 15:07:47.036875 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2445, in _connection_from_session
[Mon May 25 15:07:47.038185 2015] [wsgi:error] [pid 31001]     **kw)
[Mon May 25 15:07:47.041732 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 880, in connection
[Mon May 25 15:07:47.047655 2015] [wsgi:error] [pid 31001]     execution_options=execution_options)
[Mon May 25 15:07:47.049733 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 885, in _connection_for_bind
[Mon May 25 15:07:47.050413 2015] [wsgi:error] [pid 31001]     engine, execution_options)
[Mon May 25 15:07:47.050429 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 326, in _connection_for_bind
[Mon May 25 15:07:47.058288 2015] [wsgi:error] [pid 31001]     conn = bind.contextual_connect()
[Mon May 25 15:07:47.062399 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1910, in contextual_connect
[Mon May 25 15:07:47.069468 2015] [wsgi:error] [pid 31001]     self.pool.connect(),
[Mon May 25 15:07:47.070695 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 338, in connect
[Mon May 25 15:07:47.070850 2015] [wsgi:error] [pid 31001]     return _ConnectionFairy._checkout(self)
[Mon May 25 15:07:47.070864 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 645, in _checkout
[Mon May 25 15:07:47.070872 2015] [wsgi:error] [pid 31001]     fairy = _ConnectionRecord.checkout(pool)
[Mon May 25 15:07:47.117500 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 440, in checkout
[Mon May 25 15:07:47.117774 2015] [wsgi:error] [pid 31001]     rec = pool._do_get()
[Mon May 25 15:07:47.118112 2015] [wsgi:error] [pid 31001]   File "/shared/software/flamenco/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 960, in _do_get
[Mon May 25 15:07:47.118125 2015] [wsgi:error] [pid 31001]     (self.size(), self.overflow(), self._timeout))
[Mon May 25 15:07:47.125561 2015] [wsgi:error] [pid 31001] TimeoutError: QueuePool limit of size 10 overflow 10 reached, connection timed out, timeout 30
```

Killing all workers and restarting the server solves the issue, so it's something related to the excessive pressure that workers make on the manager.

**Comment by cyprusglobe** [comment]
Have you looked into this?
http://stackoverflow.com/questions/3360951/sql-alchemy-connection-time-out

**Comment by fsiddi** [comment]
Looks like we have to improve our queries. For the moment the problem is solved.
