### ISSUE TITLE
(Dashboard) TemplateNotFound: layout.html

### ISSUE THREAD

**Issue by stefankamoda** [armadillica/flamenco#146]
After starting the server and dashboard I get an error when browsing to http://localhost:8888/ which redirects to http://localhost:8888/jobs/. It looks like layout.html used to be committed but was excluded a few commits back. Should it be compiled automatically? Am I missing a config step? Here's the full debug output.

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app

    response = self.make_response(self.handle_exception(e))

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request

    rv = self.dispatch_request()

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/cpp/flamenco/flamenco/dashboard/application/controllers/jobs.py", line 27, in index

    return render_template('jobs/index.html', title='jobs')

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template

    context, ctx.app)

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render

    rv = template.render(context)

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render

    return self.environment.handle_exception(exc_info, True)

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] reraise(exc_type, exc_value, tb)

    File "/home/cpp/flamenco/flamenco/dashboard/application/templates/jobs/index.html", line 1, in top-level template code

    {% extends "layout.html" %}

    File "/home/cpp/flamenco/venv/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source

    raise TemplateNotFound(template)

**Comment by TheHeadSage** [comment]
I've got this issue as well, on a fresh install. After copying layout.html from the flamenco-2.0.0-beta.1 release to the correct location now results in this error:

BuildError: ('main.tasks_index', {}, None)

```
Traceback (most recent call last)
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/{USER}/git/flamenco/flamenco/dashboard/application/controllers/jobs.py", line 27, in index
return render_template('jobs/index.html', title='jobs')
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
context, ctx.app)
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
rv = template.render(context)
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
return self.environment.handle_exception(exc_info, True)
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/{USER}/git/flamenco/flamenco/dashboard/application/templates/jobs/index.html", line 1, in top-level template code
{% extends "layout.html" %}
File "/home/{USER}/git/flamenco/flamenco/dashboard/application/templates/layout.html", line 84, in top-level template code
<a href="{{ url_for('main.tasks_index') }}">Tasks</a>
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
return appctx.app.handle_url_build_error(error, endpoint, values)
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
reraise(exc_type, exc_value, tb)
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
force_external=external)
File "/home/{USER}/git/flamenco/flamenco/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1678, in build
raise BuildError(endpoint, values, method)
BuildError: ('main.tasks_index', {}, None)
```

To reinterate @stefankamoda 's question, is there a config step we are missing for an initial install?

**Comment by peppelinux** [comment]
Something similar

127.0.0.1 - - [02/Aug/2015 00:54:11] "GET /jobs/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/dashboard/application/controllers/jobs.py", line 27, in index
    return render_template('jobs/index.html', title='jobs')
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/dashboard/application/templates/jobs/index.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: layout.html


(Flamenco.io)wert@maker:~/Progs/Flamenco.io/flamenco/flamenco$ find | grep layout
./dashboard/src/jade/layout.jade
(Flamenco.io)wert@maker:~/Progs/Flamenco.io/flamenco/flamenco$ find | grep .html
./dashboard/application/templates/managers/view.html
./dashboard/application/templates/errors/500.html
./dashboard/application/templates/errors/404.html
./dashboard/application/templates/browse_modal.html
./dashboard/application/templates/projects/index.html
./dashboard/application/templates/projects/add_modal.html
./dashboard/application/templates/show_entries.html
./dashboard/application/templates/jobs/add.html
./dashboard/application/templates/jobs/view.html
./dashboard/application/templates/jobs/index.html
./dashboard/application/templates/jobs/add_modal.html
./dashboard/application/templates/tasks.html
./dashboard/application/templates/workers/view.html
./dashboard/application/templates/settings/index.html
./dashboard/application/templates/settings/status.html
./dashboard/application/templates/settings/render.html
./dashboard/application/templates/about.html

It seems that it doesn't exist at all

**Comment by jeffbean** [comment]
Before running runserver. you need to be in the `dashboard` directory and run the following

```bash 
npm install
grunt
```

This builds the jade and sass files into the application directory. worked for me on master branch.

**Comment by peppelinux** [comment]
package.json and Gruntfile.js are available only in the stable version, I saw.

I installed node.js on Debian Wheezy amd64 as root

    echo "deb http://ftp.us.debian.org/debian wheezy-backports main" >> /etc/apt/sources.list
    apt-get update
    apt-get install nodejs nodejs-legacy curl
    curl -L --insecure https://www.npmjs.org/install.sh | bash

Important, install grunt-cli first, ruby and sass

    npm install -g grunt-cli
    apt-get install ruby
    gem install sass

Go to dashboard folder and, finally. run grunt

    cd /home/$USER/Progs/Flamenco.io/flamenco/flamenco/dashboard
    grunt

**Comment by fsiddi** [comment]
Really sorry for not answering for all this time. Thanks to @peppelinux and @jeffbean for their answers! I've updated the readme accordingly. Let me know if it can be improved further.
