### ISSUE TITLE
missing module lockfile?

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#147]
Testing the latest flamenco zip file.

(venv)anton@MSI-CR610:/var/www/html/flamenco-master/flamenco/server$ ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    from application import app
  File "/var/www/html/flamenco-master/flamenco/server/application/__init__.py", line 36, in <module>
    from modules.projects import ProjectListApi
  File "/var/www/html/flamenco-master/flamenco/server/application/modules/projects/__init__.py", line 10, in <module>
    from application.modules.jobs.model import Job
  File "/var/www/html/flamenco-master/flamenco/server/application/modules/jobs/__init__.py", line 37, in <module>
    from application.modules.tasks import TaskApi
  File "/var/www/html/flamenco-master/flamenco/server/application/modules/tasks/__init__.py", line 12, in <module>
    from lockfile import LockFile, LockTimeout
ImportError: No module named lockfile
(venv)anton@MSI-CR610:/var/www/html/flamenco-master/flamenco/server$

**Comment by antonvdh** [comment]
pip install lockfile
