### ISSUE TITLE
sqlalchemy.exc.OperationalError: (OperationalError) near "DROP": syntax error u'ALTER TABLE job DROP COLUMN tasks_count' ()

### ISSUE THREAD

**Issue by peppelinux** [armadillica/flamenco#148]
(Flamenco.io)wert@maker:~/Progs/Flamenco.io/flamenco/flamenco/server$ lsb_release -a
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch

(Flamenco.io)wert@maker:~/Progs/Flamenco.io/flamenco/flamenco/server$ python manage.py runserver
INFO:alembic.migration:Context impl SQLiteImpl.
INFO:alembic.migration:Will assume non-transactional DDL.
Automatic DB Upgrade
Press Ctrl+C when finished
INFO  [alembic.migration] Context impl SQLiteImpl.
INFO  [alembic.migration] Will assume non-transactional DDL.
INFO  [alembic.migration] Running upgrade  -> 3fc5f3e23c05, initial setup
INFO  [alembic.migration] Running upgrade 3fc5f3e23c05 -> 1fa7caa8a01f, render path
INFO  [alembic.migration] Running upgrade 1fa7caa8a01f -> 376650d684d7, empty message
INFO  [alembic.migration] Running upgrade 376650d684d7 -> 3e29792080f3, rename job_managers
INFO  [alembic.migration] Running upgrade 3e29792080f3 -> 333fa88f21fa, running_tasks column
INFO  [alembic.migration] Running upgrade 333fa88f21fa -> 593c59c4c834, empty message
INFO  [alembic.migration] Running upgrade 593c59c4c834 -> 4e25f581d8bd, virtual workers
INFO  [alembic.migration] Running upgrade 4e25f581d8bd -> 28015a6e5b8, uuid for managers
INFO  [alembic.migration] Running upgrade 28015a6e5b8 -> 4bbcb4d706ef, Dropping Workers and new Jobs
INFO  [alembic.migration] Running upgrade 4bbcb4d706ef -> 2c82132f2ae3, Add child to Task
INFO  [alembic.migration] Running upgrade 2c82132f2ae3 -> 1a8440d3eaad, Add parser to Task
INFO  [alembic.migration] Running upgrade 1a8440d3eaad -> 1dbef96b8352, Add time_cost to Task
INFO  [alembic.migration] Running upgrade 1dbef96b8352 -> acabe34eef9, job creation datetime
INFO  [alembic.migration] Running upgrade acabe34eef9 -> 2d33ab39d177, Adding last_activity to tasks
INFO  [alembic.migration] Running upgrade 2d33ab39d177 -> 111a89ae6a55, Log table
INFO  [alembic.migration] Running upgrade 111a89ae6a55 -> 4bb5c8ca790e, Adding tasks_count tasks_completed
INFO  [alembic.migration] Running upgrade 4bb5c8ca790e -> 3a2606d017ea, Removing tasks_count tasks_completed
Traceback (most recent call last):
  File "manage.py", line 123, in <module>
    manager.run()
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 59, in runserver
    upgrade()
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 177, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/alembic/command.py", line 165, in upgrade
    script.run_env()
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/alembic/script.py", line 390, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/alembic/util.py", line 243, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/alembic/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 72, in <module>
    run_migrations_online()
  File "migrations/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 7, in run_migrations
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/alembic/environment.py", line 742, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/alembic/migration.py", line 309, in run_migrations
    step.migration_fn(**kw)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/server/migrations/versions/3a2606d017ea_removing_tasks_count_tasks_completed.py", line 20, in upgrade
    op.drop_column('job', 'tasks_count')
  File "<string>", line 7, in drop_column
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/alembic/operations.py", line 642, in drop_column
    **kw
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 162, in drop_column
    self._exec(base.DropColumn(table_name, column, schema=schema))
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 105, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 895, in _execute_ddl
    compiled
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (OperationalError) near "DROP": syntax error u'ALTER TABLE job DROP COLUMN tasks_count' ()

**Comment by peppelinux** [comment]
(Flamenco.io)wert@maker:~/Progs/Flamenco.io/flamenco/flamenco/server$ mv application/config.py.example  application/config.py

(Flamenco.io)wert@maker:~/Progs/Flamenco.io/flamenco/flamenco/server$ python manage.py runserver
INFO:alembic.migration:Context impl SQLiteImpl.
INFO:alembic.migration:Will assume non-transactional DDL.
INFO:werkzeug: * Running on http://0.0.0.0:9999/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:alembic.migration:Context impl SQLiteImpl.
INFO:alembic.migration:Will assume non-transactional DDL.


My mistake.
