### ISSUE TITLE
global name 'Worker' is not defined

### ISSUE THREAD

**Issue by peppelinux** [armadillica/flamenco#149]
Clicking on a worker href link I found an exception (code 500)

Traceback (most recent call last):
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 446, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 550, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/flamenco-2.0.0-beta.1/flamenco/server/application/modules/workers/__init__.py", line 51, in get
    worker = Worker.query.get_or_404(worker_id)
NameError: global name 'Worker' is not defined

**Comment by peppelinux** [comment]
The problem is that I used obsolete config.py files with a new git clone.
