### ISSUE TITLE
Worker: ERROR:root:Not a ZipFile

### ISSUE THREAD

**Issue by peppelinux** [armadillica/flamenco#155]
Quering for a new task
New Task Found 1, job 1
Fetching job file 1
Extracting /tmp/flamenco-worker/1/taskfile_1.zip
Fetching support file 1
Extracting /tmp/flamenco-worker/1/tasksupportfile_1.zip
Fetching dependency http://127.0.0.1:7777/static/storage/1/dependencies_1.zip
Extracting /tmp/flamenco-worker/1/dependencies.zip
Removing bad zipfile /tmp/flamenco-worker/1/dependencies.zip
ERROR:root:Not a ZipFile
200
Running:
/home/wert/Progs/blender-2.75a-linux-glibc211-x86_64/
--enable-autoexec
-noaudio
--background
/tmp/flamenco-worker/1/1//cazzi_divano.blend
--render-output
/tmp/flamenco-worker/1/output/1/#####
--python
/tmp/flamenco-worker/1/1//pre_render.py
--render-format
EXR
-f
1
Traceback (most recent call last):
  File "manage.py", line 67, in <module>
    manager.run()
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 52, in runserver
    controllers.worker_loop()
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/worker/application/controllers.py", line 273, in worker_loop
    execute_task(task, files)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/worker/application/controllers.py", line 759, in execute_task
    run_blender_in_thread(options)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/worker/application/controllers.py", line 528, in run_blender_in_thread
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by peppelinux** [comment]
My fault !

manager linux shared path was incorrect:
/home/wert/Progs/blender-2.75a-linux-glibc211-x86_64/

becames
/home/wert/Progs/blender-2.75a-linux-glibc211-x86_64/blender

:) works

**Comment by binarypearl** [comment]
I wrote a fix for this situation in the Worker code (but haven't done a pull request yet) where I keep the Worker running but it prints out a message indicating that it can't find the Blender binary and to check the Manager config.  But I'll save the rest of the conversation on this when I do the actual pull request.

--Shaun
