### ISSUE TITLE
Tiled rendering: Server exception AttributeError: 'NoneType' object has no attribute 'endswith' (os.path.join(project.path_linux, filepath))

### ISSUE THREAD

**Issue by peppelinux** [armadillica/flamenco#156]
If I submit a tiled rendering I get:

INFO:werkzeug:192.168.27.10 - - [20/Sep/2015 03:18:51] "POST /jobs HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 446, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 550, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 642, in wrapper
    resp = f(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/server/application/modules/jobs/__init__.py", line 455, in post
    TaskApi.create_tasks(job)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/server/application/modules/tasks/__init__.py", line 107, in create_tasks
    job_compiler.compile(job, project, TaskApi.create_task)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/server/application/job_compilers/tiled_blender_render.py", line 19, in compile
    task_settings['file_path_linux'] = os.path.join(project.path_linux, filepath)
  File "/usr/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by peppelinux** [comment]
tiled_blender_render.py
Probably it worked without, on line 17, commented. I'd to try to run this way:

 #project = Project.query.filter_by(id = job.project_id).first()

**Comment by peppelinux** [comment]
The projects path wasn't properly configured !
It could be usefull to prompt, during the first run of the server, that variables to user.

Once I filled the null-path of linux and windows and osx I also filled teis render_path.
It should go, I thought. But:

INFO:werkzeug:127.0.0.1 - - [26/Sep/2015 02:52:04] "POST /jobs HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 446, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 550, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 642, in wrapper
    resp = f(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/server/application/modules/jobs/__init__.py", line 455, in post
    TaskApi.create_tasks(job)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/server/application/modules/tasks/__init__.py", line 107, in create_tasks
    job_compiler.compile(job, project, TaskApi.create_task)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/server/application/job_compilers/tiled_blender_render.py", line 30, in compile
    task_settings['frame_start']=job_settings['frame_start']
KeyError: 'frame_start'

**Comment by peppelinux** [comment]
https://github.com/armadillica/flamenco/commit/f01b31f2d1c2a7621e5b384922cdb935b9643569
