### ISSUE TITLE
Warning: Unable to open '/tmp/flamenco-worker/2/2//scene.blend': No such file or directory

### ISSUE THREAD

**Issue by peppelinux** [armadillica/flamenco#158]
```
Extracting /tmp/flamenco-worker/2/taskfile_2.zip
Fetching support file 2
Extracting /tmp/flamenco-worker/2/tasksupportfile_2.zip
Fetching dependency http://192.168.15.11:7777/static/storage/2/dependencies_2.zip
Extracting /tmp/flamenco-worker/2/dependencies.zip
Removing bad zipfile /tmp/flamenco-worker/2/dependencies.zip
ERROR:root:Not a ZipFile
200
Running:
/NFS/blenderfarm.io/progs/blender-2.75a-linux-glibc211-x86_64/blender
--enable-autoexec
-noaudio
--background
/tmp/flamenco-worker/2/2//sezione_isabella.blend
--render-output
/tmp/flamenco-worker/2/output/2/#####
--python
/tmp/flamenco-worker/2/2//pre_render.py
--render-format
PNG
-f
1
found bundled python: /NFS/blenderfarm.io/progs/blender-2.75a-linux-glibc211-x86_64/2.75/python
read blend: /tmp/flamenco-worker/2/2//sezione_isabella.blend
Warning: Unable to open '/tmp/flamenco-worker/2/2//sezione_isabella.blend': No such file or directory
```

If I delete a job, then rebuild manager and server sqllite DB, when I submit a new job the id conflicts with the old temporary files. The files are there but older, when the worker tries to get the blend file:': No such file or directory

**Comment by peppelinux** [comment]
If I purge server application/statics/storage and server.sql I get another exception:

INFO:werkzeug:192.168.15.11 - - [20/Sep/2015 04:07:45] "GET /tasks/generate?worker=maker&uuid=14bd64765f3a11e5b184001cc4936120 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 446, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 550, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/server/application/modules/tasks/__init__.py", line 518, in get
    manager = Manager.query.filter_by(uuid=manager_uuid).one()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

It needs the purge of manager.sql.
I think that would be great to have every manager and server on a mysql server, to truncate the entire server and manager databases !

**Comment by antonvdh** [comment]
How to solve ?!
I already did remove server.sqlite and manager.sqlite and old files /tmp/flamenco-worker then did new server and manager ./manage.py runserver but again:

 found bundled python: /mnt/renderstudio/blender-2.76/2.76/python read blend: /tmp/flamenco-worker/UREND-SERV-01/1/1//Baker.blend Warning: Unable to open '/tmp/flamenco-worker/UREND-SERV-01/1/1//Baker.blend': No such file or directory

**Comment by peppelinux** [comment]
Put it in a shared folder path, an NFS resource for example

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
