### ISSUE TITLE
MySQLdb - manager first run exception

### ISSUE THREAD

**Issue by peppelinux** [armadillica/flamenco#160]
```
(Flamenco.io)wert@goose:/NFS/blenderfarm.io/progs/Flamenco.io/flamenco/flamenco/manager$ python manage.py runserver
INFO:alembic.migration:Context impl MySQLImpl.
INFO:alembic.migration:Will assume non-transactional DDL.
Traceback (most recent call last):
  File "manage.py", line 117, in <module>
    manager.run()
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 57, in runserver
    render_config = JobType.query.filter_by(name='simple_blender_render').first()
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2370, in first
    ret = list(self[0:1])
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2231, in __getitem__
    return list(res)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2441, in __iter__
    return self._execute_and_instances(context)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2456, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
sqlalchemy.exc.ProgrammingError: (ProgrammingError) (1146, "Table 'blenderfarm_flamenco_test.job_type' doesn't exist") 'SELECT job_type.id AS job_type_id, job_type.name AS job_type_name, job_type.properties AS job_type_properties, job_type.status AS job_type_status \nFROM job_type \nWHERE job_type.name = %s \n LIMIT %s' ('simple_blender_render', 1)
```

...server goes fine.
Anyone had a shortcut for migrate sqllite db to mysql in a hurry ? :)

**Comment by fsiddi** [comment]
Just to make sure, you are trying to start up the manager for the first time using MySQL as db backend?

**Comment by peppelinux** [comment]
Yes, the first time it doesn't fill the manager DB if this is MySQL.
I've migrate sqlite scheme and data manually but I've found some problem using the same db for manager and server in production,  so I turn back only the manager on sqlite and this is my actual production configuration.

I'd like to share the same DB for server and manager, I'd prefer one place to look at, instead of two, on different nodes/filesystem.

I've to read some more source code to understand the smart way to do a good configuration and a good work for the future. I know that the storage configuration was patched by callym, in https://github.com/armadillica/flamenco/pull/152, so I'd like to see this pull request merged before start coding forward.

What your production configuration francesco ? Do you use Mysql on server and manager too ?

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
