### ISSUE TITLE
tiled mix, manager exception: ValueError: Unknown format code 'd' for object of type 'unicode'

### ISSUE THREAD

**Issue by peppelinux** [armadillica/flamenco#162]
INFO:werkzeug:192.168.15.13 - - [26/Sep/2015 23:05:49] "GET /tasks/compiled/0?worker=n2 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 262, in error_router
    return self.handle_error(e)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 446, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/lib/python2.7/site-packages/flask_restful/__init__.py", line 550, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/manager/application/modules/tasks/__init__.py", line 191, in get
    task_command = task_compiler.compile(worker, task, add_file)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/manager/application/task_compilers/tiled_blender_render_simple_mix.py", line 41, in compile
    tiles_path = "tiled_{{0}}_{0:04d}.exr".format(settings['frame_start'])
ValueError: Unknown format code 'd' for object of type 'unicode'

Fixed in https://github.com/peppelinux/flamenco/commit/8c2e1a3c00bd35f9fb0c770e7889bf61ce8e2a8e, 

needs merge

The fault was that  settings json parsed dictionary had settings['frame_start'] as unicode type :(

{u'render_settings': u'', u'tiles': 4, u'format': u'EXR', u'frame_end': u'1', u'filepath': u'divano.blend', u'output_path_osx': u'/NFS/blenderfarm.tmp/18', u'priority': 50, u'file_path_linux': u'/NFS/blenderfarm.tmp/divano.blend', u'output_path_linux': u'/NFS/blenderfarm.tmp/18', u'file_path_osx': u'/NFS/blenderfarm.tmp/divano.blend', u'frame_start': u'1', u'file_path_win': u'/NFS/blenderfarm.tmp/divano.blend', u'output_path_win': u'/NFS/blenderfarm.tmp/18', u'command_name': u'default'}

I added a simple int() casting

**Comment by peppelinux** [comment]
https://github.com/armadillica/flamenco/commit/f01b31f2d1c2a7621e5b384922cdb935b9643569
