### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by elieli2** [armadillica/flamenco#164]
Hi. I'm trying to run all 4 servers on single Linux Mint machine. So far I've go working, server, manager and dashbord. While I'm assigning new job to worker I get this:
./manage.py runserver
```
  __ _
 / _| |
| |_| | __ _ _ __ ___   ___ _ __   ___ ___
| _ | |/ _` | '_ ` _ \ / _ \ '_ \ / __/ _ \
| | | | (_| | | | | | |  __/ | | | (_| (_) |
|_| |_|\__,_|_| |_| |_|\___|_| |_|\___\___/


Quering for a new task
New Task Found 43, job 1
Fetching job file 1
Extracting /tmp/flamenco-worker-marcin-VirtualBox/1/taskfile_1.zip
Fetching support file 1
Extracting /tmp/flamenco-worker-marcin-VirtualBox/1/tasksupportfile_1.zip
Fetching dependency http://localhost:7777/static/storage/1/dependencies_43.zip
Extracting /tmp/flamenco-worker-marcin-VirtualBox/1/dependencies.zip
Removing bad zipfile /tmp/flamenco-worker-marcin-VirtualBox/1/dependencies.zip
ERROR:root:Not a ZipFile
200
Running:
home/marcin/blender/blender
--enable-autoexec
-noaudio
--background
/tmp/flamenco-worker-marcin-VirtualBox/1/1//1.blend
--render-output
/tmp/flamenco-worker-marcin-VirtualBox/1/output/43/#####
--python
/tmp/flamenco-worker-marcin-VirtualBox/1/1//pre_render.py
--render-format
PNG
--frame-start
211
--frame-end
215
--render-anim
Traceback (most recent call last):
  File "./manage.py", line 67, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "./manage.py", line 52, in runserver
    controllers.worker_loop()
  File "/home/marcin/flamenco-master/flamenco/worker/application/controllers.py", line 273, in worker_loop
    execute_task(task, files)
  File "/home/marcin/flamenco-master/flamenco/worker/application/controllers.py", line 759, in execute_task
    run_blender_in_thread(options)
  File "/home/marcin/flamenco-master/flamenco/worker/application/controllers.py", line 528, in run_blender_in_thread
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

On server side:
```
./manage.py runseere
INFO:alembic.migration:Context impl SQLiteImpl.
INFO:alembic.migration:Will assume non-transactional DDL.
INFO:werkzeug: * Running on http://0.0.0.0:9999/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:alembic.migration:Context impl SQLiteImpl.
INFO:alembic.migration:Will assume non-transactional DDL.
```

On manager:
```
INFO:werkzeug:127.0.0.1 - - [03/Oct/2015 12:16:55] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Oct/2015 12:16:55] "POST /workers HTTP/1.1" 204 -
DEBUG:root:Scheduling
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:requests.packages.urllib3.connectionpool:"GET /tasks/generate?worker=marcin-VirtualBox&uuid=54a0b800695211e59d790800272f1482 HTTP/1.1" 200 693
INFO:werkzeug:127.0.0.1 - - [03/Oct/2015 12:16:55] "GET /tasks/compiled/0?worker=marcin-VirtualBox HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:requests.packages.urllib3.connectionpool:"PUT /tasks/41 HTTP/1.1" 204 0
INFO:werkzeug:127.0.0.1 - - [03/Oct/2015 12:16:55] "PATCH /tasks/41 HTTP/1.1" 204 -
INFO:werkzeug:127.0.0.1 - - [03/Oct/2015 12:16:55] "GET /static/storage/1/jobfile_1.zip HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Oct/2015 12:16:55] "GET /static/storage/1/jobsupportfile_1.zip HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Oct/2015 12:16:55] "GET /static/storage/1/dependencies_41.zip HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [03/Oct/2015 12:16:55] "GET /job-types/blender_simple_render HTTP/1.1" 200 -
```

Any ide what's wrong?

**Comment by peppelinux** [comment]
set your blender_path in worker config.py and in manager this way:

worker
BLENDER_PATH = '/NFS/blenderfarm.io/progs/blender-2.75a-linux-glibc211-x86_64/blender'

manager
BLENDER_PATH_LINUX = "/NFS/blenderfarm.io/progs/blender-2.75a-linux-glibc211-x86_64/blender"
