### ISSUE TITLE
Installing plugin in Blender generates multiple errors

### ISSUE THREAD

**Issue by EVMosaic** [armadillica/flamenco#170]
Attempted in Windows 10 and Ubuntu, getting similar errors on each when I hit the Update Flamenco button.

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 384, in draw
    if len(project_list(self, context)) == 0:
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 519, in project_list
    for project in project_cache:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 384, in draw
    if len(project_list(self, context)) == 0:
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 519, in project_list
    for project in project_cache:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 384, in draw
    if len(project_list(self, context)) == 0:
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 519, in project_list
    for project in project_cache:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 384, in draw
    if len(project_list(self, context)) == 0:
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 519, in project_list
    for project in project_cache:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 168, in execute
    for setting in settings_managers[manager]:
TypeError: 'int' object is not iterable

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 384, in draw
    if len(project_list(self, context)) == 0:
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 519, in project_list
    for project in project_cache:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 384, in draw
    if len(project_list(self, context)) == 0:
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 519, in project_list
    for project in project_cache:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 384, in draw
    if len(project_list(self, context)) == 0:
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 519, in project_list
    for project in project_cache:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 384, in draw
    if len(project_list(self, context)) == 0:
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 519, in project_list
    for project in project_cache:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 168, in execute
    for setting in settings_managers[manager]:
TypeError: 'int' object is not iterable

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 384, in draw
    if len(project_list(self, context)) == 0:
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 519, in project_list
    for project in project_cache:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

**Comment by fsiddi** [comment]
Is this the output of a single click? How is the addon configured (which server, etc)?

**Comment by EVMosaic** [comment]
That was probably multiple clicks there, but I wasn't sure where the first error started so apologies for the duplicates. I tried using the server on localhost and connecting to a machine on my local network running the server. The worker is on Windows 10 and the server is on Ubuntu but no combination or soloing of those two produced a working result for me.

**Comment by EVMosaic** [comment]
Ok, back in the office today, heres the results from one click, this time I'm getting some json errors too.

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 164, in execute
    settings_managers = settings_managers.json()
  File "C:\Program Files\Blender Foundation\Blender\2.76\python\lib\site-packages\requests\models.py", line 797, in json
    return json.loads(self.text, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender\2.76\python\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Blender Foundation\Blender\2.76\python\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Blender Foundation\Blender\2.76\python\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 384, in draw
    if len(project_list(self, context)) == 0:
  File "C:\Users\Eric Varela\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\render_flamenco.py", line 519, in project_list
    for project in project_cache:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

**Comment by EVMosaic** [comment]
also should note between location: and :-1 there is an "unknown location" in angle brackets.

**Comment by peppelinux** [comment]
The problem is that in your server db, in settings (or project) table, you have to set all the records != null. Try to use server with mysql and then fill that records with your paths. It will works.

**Comment by EVMosaic** [comment]
Hey, finally had a chance to play around with this and the mysql helped me debug, but ultimately was not the problem. I tracked it down to 

`flamenco/flamenco/server/application/modules/projects/__init__.py`

specifically the get method.
```
    def get(self):
        projects = {}
        count = Project.query.count()
        if count == 0:
            project = Project(name="Default Project")
            db.session.add(project)
            db.session.commit()

        for project in Project.query.all():
            projects[project.id] = dict(
                name=project.name)
```

The `projects` dictionary is constructed but never returned from the method. Adding `return projects` after the for loop fixed this problem for me.

**Comment by peppelinux** [comment]
Please fork flamenco on your repository and do a pull request, your patch will be available to all of us.
