### ISSUE TITLE
trouble starting server and manager on windows

### ISSUE THREAD

**Issue by kromar** [armadillica/flamenco#171]
i was trying to get the manager and server running on windows but im stuck with this error when i run either of them. 
do you have any idea why i get this error?

```
C:\SVN\flamenco>python ./flamenco/manager/manage.py runserverINFO:alembic.migration:Context impl SQLiteImpl.
INFO:alembic.migration:Will assume non-transactional DDL.
Automatic DB Upgrade
Press Ctrl+C when finished
Traceback (most recent call last):
File "./flamenco/manager/manage.py", line 118, in <module>
manager.run()
File "C:\Python27\lib\site-packages\flask_script\__init__.py", line 412, in run
result = self.handle(sys.argv[0], sys.argv[1:])
File "C:\Python27\lib\site-packages\flask_script\__init__.py", line 383, in handle
res = handle(*args, **config)
File "C:\Python27\lib\site-packages\flask_script\commands.py", line 216, in __call__
return self.run(*args, **kwargs)
File "./flamenco/manager/manage.py", line 38, in runserver
upgrade()
File "C:\Python27\lib\site-packages\flask_migrate\__init__.py", line 176, in upgrade
config = _get_config(directory)
File "C:\Python27\lib\site-packages\flask_migrate\__init__.py", line 45, in _get_config
config.set_main_option('script_location', directory)
File "C:\Python27\lib\site-packages\alembic\config.py", line 198, in set_main_option
self.file_config.set(self.config_ini_section, name, value)
File "C:\Python27\lib\ConfigParser.py", line 753, in set
ConfigParser.set(self, section, option, value)
File "C:\Python27\lib\ConfigParser.py", line 396, in set
raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'alembic'
````

**Comment by peppelinux** [comment]
You have to setup, please read the readme

**Comment by kromar** [comment]
ok, i  will see if i missed something in the setup

**Comment by kromar** [comment]
so i worked through  the readme again and installed all dependencies as far as i can tell and still get the same problem when trying to start the manager or server.
any help would be appreciated.

**Comment by peppelinux** [comment]
Probably it's a problem of database inconsistency, can you clean up all and start again with the git master branch instead of alpha release ?

**Comment by kromar** [comment]
i am already using the master

**Comment by fsiddi** [comment]
Might be a path position problem. Try:

```
cd ./flamenco/manager/
python manage.py runserver
```

The alembic migration files needs to be in a relative location, so run the python script from within the same folder where `manage.py` is located.

**Comment by kromar** [comment]
alright, that was indeed the issue, thanks a lot!
