### ISSUE TITLE
[addon] update flamenco server error

### ISSUE THREAD

**Issue by kromar** [armadillica/flamenco#173]
i get this error when i try to update the server in blender:

```
Traceback (most recent call last):
  File "C:\addons\render_flamenco.p
y", line 164, in execute
    settings_managers = settings_managers.json()
  File "C:\bin\Release\2.76\python\lib\site-packages\requests\models.
py", line 797, in json
    return json.loads(self.text, **kwargs)
  File "C:\bin\Release\2.76\python\lib\json\__init__.py", line 318, i
n loads
    return _default_decoder.decode(s)
  File "C:\bin\Release\2.76\python\lib\json\decoder.py", line 343, in
 decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\bin\Release\2.76\python\lib\json\decoder.py", line 361, in
 raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

location: <unknown location>:-1

location: <unknown location>:-1


```

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
