### ISSUE TITLE
can install by pip  because off egg_info failed 

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#177]
pip install -r requirements.txt 

command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mh482aho/flup
I already did:  sudo pip install --upgrade setuptools

Need some help.

**Comment by antonvdh** [comment]
pip show setuptools
---
Metadata-Version: 2.0
Name: setuptools
Version: 19.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://bitbucket.org/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: PSF or ZPL
Location: /usr/lib/python3.4/site-package

**Comment by antonvdh** [comment]
pip install -r requirements.txt 
Collecting alembic==0.7.5.post2 (from -r requirements.txt (line 1))
  Using cached alembic-0.7.5.post2.tar.gz
Collecting aniso8601==0.92 (from -r requirements.txt (line 2))
  Using cached aniso8601-0.92.tar.gz
Collecting ecdsa==0.13 (from -r requirements.txt (line 3))
  Using cached ecdsa-0.13-py2.py3-none-any.whl
Collecting Flask==0.10.1 (from -r requirements.txt (line 4))
  Using cached Flask-0.10.1.tar.gz
Collecting Flask-Migrate==1.3.1 (from -r requirements.txt (line 5))
  Using cached Flask-Migrate-1.3.1.tar.gz
Collecting Flask-RESTful==0.3.2 (from -r requirements.txt (line 6))
  Using cached Flask_RESTful-0.3.2-py2.py3-none-any.whl
Collecting Flask-Script==2.0.5 (from -r requirements.txt (line 7))
  Using cached Flask-Script-2.0.5.tar.gz
Collecting Flask-SQLAlchemy==2.0 (from -r requirements.txt (line 8))
  Using cached Flask-SQLAlchemy-2.0.tar.gz
Collecting flup==1.0.2 (from -r requirements.txt (line 9))
  Using cached flup-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-z_1oh6v4/flup/setup.py", line 2, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-build-z_1oh6v4/flup/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

Could it be a problem with ez_setup.py and the python3 version?

**Comment by antonvdh** [comment]
Solved problem was the python version.
