### ISSUE TITLE
improve install readme

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#182]
Please improve the install readme file.
For example add the path name where to install Flamenco server to be linked to the mysql container.
Is this /media/data/docker/server ?

I get the error missing manage.py  after armadillica/flamenco_server_dev
Container cannot be started.

**Comment by AdmiralPotato** [comment]
+1

**Comment by antonvdh** [comment]
anton@flamenco:/media/data/flamenco/flamenco/server$ docker run -ti -p 9999:9999 --name flamenco_server --link mysql \            
> -v /media/data/flamenco/flamenco/server:/data/git/server \                                                                      
> -v /media/data/flamenco_data/storage/shared:/data/storage/shared \                                                              
> -v /media/data/flamenco_data/storage/server:/data/storage/server \                                                              
> armadillica/flamenco_server_dev                                                                                                 
Traceback (most recent call last):                                                                                                
  File "manage.py", line 97, in <module>                                                                                          
    manager.run()                                                                                                                 
  File "/data/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run                                  
    result = self.handle(sys.argv[0], sys.argv[1:])                                                                               
  File "/data/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/data/venv/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 63, in setup_db
    conn = engine.connect()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1890, in connect
    return self._connection_cls(self, **kwargs)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 60, in __init__
    self.__connection = connection or engine.raw_connection()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1964, in raw_connection
    return self.pool.unique_connection()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 280, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 645, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 440, in checkout
    rec = pool._do_get()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 964, in _do_get
    return self._create_connection()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 285, in _create_connection
    return _ConnectionRecord(self)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 411, in __init__
    self.connection = self.__connect()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 539, in __connect
    connection = self.__pool._creator()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 96, in connect
    connection_invalidated=invalidated
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 90, in connect
    return dialect.connect(*cargs, **cparams)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/data/venv/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/data/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (OperationalError) (2005, "Unknown MySQL server host 'mysql_flamenco' (0)") None None
Traceback (most recent call last):
  File "manage.py", line 97, in <module>
    manager.run()
  File "/data/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/data/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/data/venv/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 79, in runserver
    setup_db()
  File "manage.py", line 63, in setup_db
    conn = engine.connect()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1890, in connect
    return self._connection_cls(self, **kwargs)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 60, in __init__
    self.__connection = connection or engine.raw_connection()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1964, in raw_connection
    return self.pool.unique_connection()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 280, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 645, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 440, in checkout
    rec = pool._do_get()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 964, in _do_get
    return self._create_connection()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 285, in _create_connection
    return _ConnectionRecord(self)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 411, in __init__
    self.connection = self.__connect()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 539, in __connect
    connection = self.__pool._creator()
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 96, in connect
    connection_invalidated=invalidated
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 90, in connect
    return dialect.connect(*cargs, **cparams)
  File "/data/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/data/venv/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/data/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (OperationalError) (2005, "Unknown MySQL server host 'mysql_flamenco' (0)") None None
anton@flamenco:/media/data/flamenco/flamenco/server$ 

And now ?

**Comment by antonvdh** [comment]
Another month passed by.
Please improve the install readme.

**Comment by peppelinux** [comment]
mysql_flamenco is the server hostname but it doesn't exists.

just use ip address or resolv that name in dns/hostfile.
isn't it ?

**Comment by antonvdh** [comment]
Yes I use ip or dns hostfile which was set in the config.py for server manager dashboard and worker.

**Comment by peppelinux** [comment]
..and why doesn't resolv that name ?
Try to ping it from terminal.

**Comment by antonvdh** [comment]
Ping dns name is no problem etc/resolv.conf and hosts are set correctly. Ip adress ping also works.

**Comment by antonvdh** [comment]
Ps Docker is not working when there is a mysql server already running.!!

**Comment by fsiddi** [comment]
I jus pushed 7a1b7758842c435af8746804e196af782f7fe04e which might solve the problem. Try to run the server command again.

**Comment by antonvdh** [comment]
Build a new s server Ubuntu 14.04. 
Please improve the readme !  Sorry for wasting your time.

anton@Renderfarm:/media/data$ docker run -ti -p 3306:3306 --name mysql -e MySQL_ROOT_PASSWORD=root mysql
FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create?name=mysql: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS? 
anton@Renderfarm:/media/data$

**Comment by antonvdh** [comment]
Trying as sudo:
anton@Renderfarm:/media/data$ sudo docker run -ti -p 3306:3306 --name mysql -e MySQL_ROOT_PASSWORD=root mysql
Unable to find image 'mysql:latest' locally
latest: Pulling from mysql
77e39ee82117: Pull complete 
5eb1402f0414: Pull complete 
19f165e6c765: Pull complete 
2a2906e625e9: Pull complete 
eee9d439c32b: Pull complete 
7bc97b69e31a: Pull complete 
49b6c385b550: Pull complete 
52bc57b38d66: Pull complete 
0d1e1e5612f2: Pull complete 
343e5dc8d81c: Pull complete 
c9becf6b6289: Pull complete 
9f906389479d: Pull complete 
9756a6920639: Pull complete 
3bc529130b33: Pull complete 
1ff1f2f44ef0: Pull complete 
596847483ae2: Pull complete 
mysql:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:83e23c54b891840545c6e0908dc86ebe390f95736f37dcbfaf1b87b77178d648
Status: Downloaded newer image for mysql:latest
error: database is uninitialized and password option is not specified 
  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
anton@Renderfarm:/media/data$

**Comment by fsiddi** [comment]
I am not sure I understand your message. It looks like you are having a docker problem now.
How would you suggest we improve the readme?

**Comment by antonvdh** [comment]
I am using a fresh new installed ubuntu 14.04 server. The docker install as described in the readme is not possible. Sorry but the readme is imo incomplete.

**Comment by antonvdh** [comment]
OK I have finally docker up and running tested with for example  docker run hello-world
Need a little help what did I forget, password ?

anton@Renderfarm:/media/data$ docker run -ti -p 3306:3306 --name mysql -e MySQL_ROOT_PASSWORD=root mysql
error: database is uninitialized and password option is not specified 
  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
anton@Renderfarm:/media/data$

**Comment by Eibriel** [comment]
Duplicated with #174
