### ISSUE TITLE
pip install -r requirements.txt fails

### ISSUE THREAD

**Issue by antonvdh** [armadillica/flamenco#183]
```
Downloading/unpacking MySQL-python==1.2.5 (from -r requirements.txt (line 15))
  Downloading MySQL-python-1.2.5.zip (108kB): 108kB downloaded
  Running setup.py (path:/media/data/flamenco/flamenco/venv/build/MySQL-python/setup.py) egg_info for package MySQL-python
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/media/data/flamenco/flamenco/venv/build/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/media/data/flamenco/flamenco/venv/build/MySQL-python/setup.py", line 17, in <module>

    metadata, options = get_config()

  File "setup_posix.py", line 43, in get_config

    libs = mysql_config("libs_r")

  File "setup_posix.py", line 25, in mysql_config

    raise EnvironmentError("%s not found" % (mysql_config.path,))

EnvironmentError: mysql_config not found

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /media/data/flamenco/flamenco/venv/build/MySQL-python
Storing debug log for failure in /home/anton/.pip/pip.logTraceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/media/data/flamenco/flamenco/venv/build/MySQL-python/setup.py", line 17, in <module>

    metadata, options = get_config()

  File "setup_posix.py", line 43, in get_config

    libs = mysql_config("libs_r")

  File "setup_posix.py", line 25, in mysql_config

    raise EnvironmentError("%s not found" % (mysql_config.path,))

EnvironmentError: mysql_config not found

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /media/data/flamenco/flamenco/venv/build/MySQL-python
Storing debug log for failure in /home/anton/.pip/pip.log
```

**Comment by Eibriel** [comment]
Hi, please always add a description of the issue, even if it could be deducted from the log.
You have Flamenco up and running now, so I'm closing this now.
