### ISSUE TITLE
Error trying to run worker

### ISSUE THREAD

**Issue by binarypearl** [armadillica/flamenco#200]
I now have python 3.5 and am using a virtualenv.  I am getting the error below when trying to run flamenco-worker.  Do you know what could be happening?

fyi:  This is the first time I worked with virtualenv, so my directory structure is a little confusing.  I installed both the manager (which started successfully) and the worker in:  /mnt/backups/blender/flamenco_v2/worker/smm/*)

```
(smm) foo@rendernavi2 /mnt/backups/blender/flamenco_v2/worker/smm $ ./bin/flamenco-worker 
2017-06-21 08:15:30,055     INFO flamenco_worker.worker.FlamencoWorker Starting up
2017-06-21 08:15:30,055     INFO flamenco_worker.worker.FlamencoWorker Registering at manager
2017-06-21 08:15:30,056    ERROR flamenco_worker.cli Uncaught exception!
Traceback (most recent call last):
  File "/mnt/backups/blender/flamenco_v2/worker/smm/lib/python3.5/site-packages/flamenco_worker/cli.py", line 97, in main
    loop.run_until_complete(fworker.startup())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/mnt/backups/blender/flamenco_v2/worker/smm/lib/python3.5/site-packages/flamenco_worker/worker.py", line 112, in startup
    await self.register_at_manager(may_retry_loop=may_retry_loop)
  File "/mnt/backups/blender/flamenco_v2/worker/smm/lib/python3.5/site-packages/flamenco_worker/worker.py", line 188, in register_at_manager
    may_retry_loop=may_retry_loop,
  File "/mnt/backups/blender/flamenco_v2/worker/smm/lib/python3.5/site-packages/flamenco_worker/worker.py", line 143, in _keep_posting_to_manager
    resp = await self.manager.post(url, **post_kwargs)
  File "/mnt/backups/blender/flamenco_v2/worker/smm/lib/python3.5/site-packages/flamenco_worker/upstream.py", line 28, in post
    return await self.client_request('POST', *args, loop=loop, **kwargs)
  File "/mnt/backups/blender/flamenco_v2/worker/smm/lib/python3.5/site-packages/flamenco_worker/upstream.py", line 86, in client_request
    headers['User-Agent'] = self.user_agent()
TypeError: unhashable type: 'FlamencoManager'
2017-06-21 08:15:30,058  WARNING flamenco_worker.cli Closing asyncio loop
2017-06-21 08:15:30,058  WARNING flamenco_worker.cli Flamenco Worker is shut down
(smm) foo@rendernavi2 /mnt/backups/blender/flamenco_v2/worker/smm $ 
```

--Shaun

**Comment by sybrenstuvel** [comment]
> fyi: This is the first time I worked with virtualenv, so my directory structure is a little confusing. I installed both the manager (which started successfully) and the worker in: /mnt/backups/blender/flamenco_v2/worker/smm/*)

This doesn't sound like a good idea. The Manager isn't even written in Python, so it doesn't even have a concept of virtualenvs. I suggest you keep things clean, and not mix up the Manager and the Worker.

Can you post your flamenco-worker.cfg file?

**Comment by binarypearl** [comment]
Gotcha, I'll break the Manager back out (it started successfully either way).

flamenco-worker.cfg:
[flamenco-worker]
manager_url = http://192.168.1.202:8083/
task_types = sleep blender-render file-management
task_update_queue_db = flamenco-worker.db

may_i_run_interval_seconds = 5
push_log_max_interval_seconds = 20
push_log_max_entries = 200
push_act_max_interval_seconds = 10


[loggers]
keys = root,flamenco_worker

[logger_root]
level = WARNING
handlers = console,file

[logger_flamenco_worker]
level = INFO
qualname = flamenco_worker
handlers = console,file
propagate = 0

[handlers]
keys = console,file

[handler_console]
class = logging.StreamHandler
formatter = flamenco
args = (sys.stderr,)

[handler_file]
class = logging.handlers.TimedRotatingFileHandler
formatter = flamenco
# (filename, when, interval, backupCount, encoding, delay, utc, atTime=None)
# Be aware that tilde expansion is *not* performed on the path.
args = ('/tmp/flamenco-worker.log', 'midnight', 1, 7, 'utf8', True, True)

[formatters]
keys = flamenco

[formatter_flamenco]
format = %(asctime)-15s %(levelname)8s %(name)s %(message)s

**Comment by sybrenstuvel** [comment]
Select your text and hit the "Code" button. That'll mark it as code (effectively just placing triple backticks before/after it). I've just done that for you to make it easier to read for me ;-)

**Comment by sybrenstuvel** [comment]
I don't see anything in the config that could cause this error. Can you activate the virtualenv, type `pip3 freeze`, and paste the output here?

**Comment by binarypearl** [comment]
I broke out the Manager so it's no longer in the virtenv.  See below:
```
(smm) foo@rendernavi2 /mnt/backups/blender/flamenco_v2/worker/smm $ pip3 freeze
attrs==17.2.0
certifi==2017.4.17
chardet==3.0.4
flamenco-worker==2.0.5
idna==2.5
requests==2.18.1
urllib3==1.21.1
(smm) foo@rendernavi2 /mnt/backups/blender/flamenco_v2/worker/smm $
```

**Comment by sybrenstuvel** [comment]
That was it -- attrs had a backward-incompatible change between versions 16 and 17. Can you try this version and see if it works on your machine too?

[flamenco-worker-2.0.6b1.zip](https://github.com/armadillica/flamenco/files/1091752/flamenco-worker-2.0.6b1.zip)

You can just install the `.whl` from that file -- GitHub doesn't allow me to upload `.whl` files, so I just uploaded the entire zip.

**Comment by binarypearl** [comment]
Great, will do.  I'm at work now so I'll try it out tonight.

--Shaun

**Comment by binarypearl** [comment]
That worked, the worker started!  

--Shaun
