### ISSUE TITLE
Errors when clicking 'Render on Flamenco' button

### ISSUE THREAD

**Issue by binarypearl** [armadillica/flamenco#201]
Getting closer...

I got the Blender Cloud add-on installed and logged in.  I brought up an existing .blend file and then clicked on the 'Save 2.78 settings' button. I set the 'Job File Path' and 'Job Output Path' to directories on my shared storage.

When I click on the 'Render on Flamenco' button, nothing appears to happen.  When I looked at stdout, I get the errors below.  I am running Blender 2.78c.  I did notice there are empty directories getting created in the job_storage/ folder.

Any idea on what is happening here?

--Shaun

```

foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ Exception while running task: module 'io_blend_utils' has no attribute 'pythonpath'
Exception from asynchronous task
Traceback (most recent call last):
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 279, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 162, in async_execute
    outfile, missing_sources = await self.bam_pack(filepath)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 328, in bam_pack
    missing_sources = await bam_interface.bam_copy(filepath, outfile, exclusion_filter)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/bam_interface.py", line 80, in bam_copy
    env={'PYTHONPATH': io_blend_utils.pythonpath()},
AttributeError: module 'io_blend_utils' has no attribute 'pythonpath'
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py:138> exception=AttributeError("module 'io_blend_utils' has no attribute 'pythonpath'",)>: resulted in exception
Traceback (most recent call last):
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 279, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 162, in async_execute
    outfile, missing_sources = await self.bam_pack(filepath)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 328, in bam_pack
    missing_sources = await bam_interface.bam_copy(filepath, outfile, exclusion_filter)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/bam_interface.py", line 80, in bam_copy
    env={'PYTHONPATH': io_blend_utils.pythonpath()},
AttributeError: module 'io_blend_utils' has no attribute 'pythonpath'
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py:138> exception=AttributeError("module 'io_blend_utils' has no attribute 'pythonpath'",)>: resulted in exception
Traceback (most recent call last):
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 279, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 162, in async_execute
    outfile, missing_sources = await self.bam_pack(filepath)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 328, in bam_pack
    missing_sources = await bam_interface.bam_copy(filepath, outfile, exclusion_filter)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/bam_interface.py", line 80, in bam_copy
    env={'PYTHONPATH': io_blend_utils.pythonpath()},
AttributeError: module 'io_blend_utils' has no attribute 'pythonpath'
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py:138> exception=AttributeError("module 'io_blend_utils' has no attribute 'pythonpath'",)>: resulted in exception
Traceback (most recent call last):
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 279, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 162, in async_execute
    outfile, missing_sources = await self.bam_pack(filepath)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 328, in bam_pack
    missing_sources = await bam_interface.bam_copy(filepath, outfile, exclusion_filter)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/bam_interface.py", line 80, in bam_copy
    env={'PYTHONPATH': io_blend_utils.pythonpath()},
AttributeError: module 'io_blend_utils' has no attribute 'pythonpath'
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py:138> exception=AttributeError("module 'io_blend_utils' has no attribute 'pythonpath'",)>: resulted in exception
Traceback (most recent call last):
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 279, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 162, in async_execute
    outfile, missing_sources = await self.bam_pack(filepath)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 328, in bam_pack
    missing_sources = await bam_interface.bam_copy(filepath, outfile, exclusion_filter)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/bam_interface.py", line 80, in bam_copy
    env={'PYTHONPATH': io_blend_utils.pythonpath()},
AttributeError: module 'io_blend_utils' has no attribute 'pythonpath'
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py:138> exception=AttributeError("module 'io_blend_utils' has no attribute 'pythonpath'",)>: resulted in exception
Traceback (most recent call last):
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 94, in kick_async_loop
    res = task.result()
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/async_loop.py", line 279, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/blender-2.78c-linux-glibc219-x86_64/2.78/python/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 162, in async_execute
    outfile, missing_sources = await self.bam_pack(filepath)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/__init__.py", line 328, in bam_pack
    missing_sources = await bam_interface.bam_copy(filepath, outfile, exclusion_filter)
  File "/home/foo/.config/blender/2.78/scripts/addons/blender_cloud/flamenco/bam_interface.py", line 80, in bam_copy
    env={'PYTHONPATH': io_blend_utils.pythonpath()},
AttributeError: module 'io_blend_utils' has no attribute 'pythonpath'

```

**Comment by sybrenstuvel** [comment]
I forgot that Blender 2.78c had a much older version of the `io_blend_utils` add-on than current master. I'll have to think about how we'd solve this -- we can either require Blender 2.79 as minimum version for Flamenco support, or we can bundle a newer version of [BAM](https://pypi.python.org/pypi/blender-bam) with the Blender Cloud add-on.

For now you should be able to get things to run with the [testbuild](http://download.blender.org/release/Blender2.79/) or a [daily build](https://builder.blender.org/download/) of Blender 2.79. Personally I'd go with the latter ;-)

**Comment by binarypearl** [comment]
On the daily build link I downloaded: https://builder.blender.org/download/blender-2.78-19791760880-linux-glibc219-x86_64.tar.bz2.  It's listed at the top as version 2.78.5, so I assume that's close enough to 2.79?

It looks like it solved the issue reported above.  But now I'm getting a 403 Forbidden message when clicking on 'Render on Flamenco'.  I am logged in through the Blender add-on.  I noticed that when I used a web browser where I am logged into the Blender cloud, I can access the link https://cloud.blender.org/api/flamenco/jobs successfully.  On a web browser where I am not logged into the Blender Cloud, I get the same 403 message below.


```
Error: Error creating Flamenco job: Failed. Response status: 403. Response message: FORBIDDEN. Request URL: https://cloud.blender.org/api/flamenco/jobs. Error message: {"_status": "ERR", "_code": 403, "_message": "You don't have the permission to access the requested resource. It is either read-protected or not readable by the server."}
```

**Comment by sybrenstuvel** [comment]
> On the daily build link I downloaded: https://builder.blender.org/download/blender-2.78-19791760880-linux-glibc219-x86_64.tar.bz2. It's listed at the top as version 2.78.5, so I assume that's close enough to 2.79?

That's correct -- it won't be marked as 2.79 until it's a Release Candidate.

Which project do you have selected in the Blender Cloud add-on?

**Comment by binarypearl** [comment]
I tried the 2.79 testbuild as well, same thing.

I have the project 'smm_test_render' selected.  Here is a screenshot of my user preferences:
![selection_001](https://user-images.githubusercontent.com/839047/27432025-8b61e08a-571c-11e7-9e42-f444db921352.png)

--Shaun

**Comment by sybrenstuvel** [comment]
That all looks good. Can you post the full stack trace of the exception?

**Comment by binarypearl** [comment]
Unfortunately the 403 message listed above is all of the output that I am getting.

I doubt it's related but I'll post this anyway:

The output of the manager on my local system is giving these messages:
`ERRO[2017-06-22T08:36:01-04:00] TaskScheduler: Error fetching task for 192.168.1.202 (rendernavi2): exception: the $unwind field path must be specified as a string`

The output of the worker on my local system is giving these messages:
`2017-06-22 08:35:51,816  WARNING flamenco_worker.worker.FlamencoWorker Error 500 fetching new task, will retry in 10 seconds.`

Since I am getting a 403, I'm definitely hitting the Flamenco server.  (I also flushed all iptables rules out just to be on the safe side).  Even in the user preferences, It's hitting other urls successfully because it's able to pull/find my manager name and project.  So that tells me I am logged in.

Which then has me thinking, are there any other addons that I would need to install manually (pillar, etc?).  I was thinking maybe I don't have something installed and it's returning an error because some component is missing.

It's almost like it's making this particular call to https://cloud.blender.org/api/flamenco/jobs without being authenticated.

Got to ready for work, hope this helps.  Also thinking maybe I can try to put in some additional debug messages into the blender add-on that might shed some light into what's happening.

--Shaun

**Comment by sybrenstuvel** [comment]
> Unfortunately the 403 message listed above is all of the output that I am getting.

Also on the terminal? If so, could you configure logging for me? Place this in `~/.config/blender/2.78/scripts/startup/config_logging.py`:

```
import logging.config

LOGGING = {
    'version': 1,
    'formatters': {
        'default': {'format': '%(asctime)-15s %(levelname)8s %(name)s %(message)s'}
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
            'stream': 'ext://sys.stderr',
        },
    },
    'loggers': {
        'blender_id': {'level': 'INFO'},
        'blender_cloud': {'level': 'INFO'},
        'pillarsdk': {'level': 'INFO'},
        'blender_cloud.pillar': {'level': 'INFO'},
        'blender_cloud.wheels': {'level': 'INFO'},
        'blender_cloud.texture_browser': {'level': 'INFO'},
        'bpy.ops.pillar': {'level': 'INFO'},
        'requests': {'level': 'INFO'},
    },
    'root': {
        'level': 'INFO',
        'handlers': [
            'console',
        ],
    }
}
logging.config.dictConfig(LOGGING)

def register():
    pass
```

That will enable more fine-grained logging, so we can see what's going on.

> `ERRO[2017-06-22T08:36:01-04:00] TaskScheduler: Error fetching task for 192.168.1.202 (rendernavi2): exception: the $unwind field path must be specified as a string`

Which version of MongoDB are you running?

> Which then has me thinking, are there any other addons that I would need to install manually (pillar, etc?). I was thinking maybe I don't have something installed and it's returning an error because some component is missing.

Nope, this should be it.

> It's almost like it's making this particular call to https://cloud.blender.org/api/flamenco/jobs without being authenticated.

That's the job creation call, it does a POST with the new job info. It certainly should be authenticated, since an unauthenticated POST is never accepted (and we've been using Flamenco for months here).

**Comment by binarypearl** [comment]
Mongodb version:  1:2.4.9-1ubuntu2

Here is the output of my entire session with the config_logging.py script:

```
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ /opt/blender-2.78-19791760880-linux-glibc219-x86_64/blender&
[1] 19726
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ Read prefs: /home/foo/.config/blender/2.78/config/userpref.blend
found bundled python: /opt/blender-2.78-19791760880-linux-glibc219-x86_64/2.78/python
2017-06-22 09:09:34,666     INFO blender_cloud.blender Updating internal state to reflect extensions enabled on current project .
2017-06-22 09:09:34,667     INFO blender_cloud.attract Deactivating Attract
2017-06-22 09:09:34,667     INFO blender_cloud.flamenco Deactivating Flamenco
2017-06-22 09:09:34,667     INFO blender_cloud.blender Project extensions: set()
Read blend: /home/foo/dl/blender/speed_testing/portals2.blend
2017-06-22 09:10:17,573     INFO bpy.ops.pillar.sync Starting
2017-06-22 09:10:17,585     INFO blender_cloud.blender Communicating with Blender Cloud
2017-06-22 09:10:17,585     INFO bpy.ops.pillar.sync Performing action PUSH
2017-06-22 09:10:17,585     INFO blender_cloud.cache Storing cache in /home/foo/.cache/blender/blender_cloud/shaunmiller1024@gmail.com/blender_cloud_http
2017-06-22 09:10:17,623     INFO requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): cloud.blender.org
2017-06-22 09:10:18,137     INFO bpy.ops.pillar.sync Credentials okay.
2017-06-22 09:10:18,278     INFO requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): cloud.blender.org
2017-06-22 09:10:18,769     INFO bpy.ops.pillar.sync Saved user preferences to disk before pushing to cloud.
trying to save userpref at /home/foo/.config/blender/2.78/config/userpref.blend ok
2017-06-22 09:10:18,769     INFO blender_cloud.blender Uploading userpref.blend
2017-06-22 09:10:20,033     INFO pillarsdk.api Pillar-Request-Id: 6dad8914-0915-48ce-a34a-aa0d8ece535c
2017-06-22 09:10:20,903     INFO blender_cloud.blender Refreshing available Blender versions.
2017-06-22 09:10:21,184     INFO blender_cloud.blender Settings pushed to Blender Cloud.
2017-06-22 09:10:21,185     INFO bpy.ops.pillar.sync Signalling that we want to cancel anything that's running.
2017-06-22 09:10:25,786     INFO blender_cloud.async_loop.AsyncModalOperatorMixin Starting
2017-06-22 09:10:25,797     INFO blender_cloud.async_loop.AsyncModalOperatorMixin Checking credentials
2017-06-22 09:10:25,919     INFO blender_cloud.async_loop.AsyncModalOperatorMixin Credentials okay.
2017-06-22 09:10:25,919     INFO blender_cloud.async_loop.AsyncModalOperatorMixin Going to fetch projects for user 59478a892487bb082c99b394
2017-06-22 09:10:26,200     INFO blender_cloud.blender Updating internal state to reflect extensions enabled on current project 5948809a2487bb0998cf03ca.
2017-06-22 09:10:26,200     INFO blender_cloud.attract Deactivating Attract
2017-06-22 09:10:26,200     INFO blender_cloud.flamenco Deactivating Flamenco
2017-06-22 09:10:26,200     INFO blender_cloud.blender Project extensions: {'flamenco'}
2017-06-22 09:10:26,201     INFO blender_cloud.flamenco Activating Flamenco
2017-06-22 09:10:26,201     INFO blender_cloud.async_loop.AsyncModalOperatorMixin Signalling that we want to cancel anything that's running.
2017-06-22 09:10:30,180     INFO blender_cloud.flamenco.FLAMENCO_OT_fmanagers Starting
2017-06-22 09:10:30,200     INFO blender_cloud.flamenco.FLAMENCO_OT_fmanagers Checking credentials
2017-06-22 09:10:30,357     INFO blender_cloud.flamenco.FLAMENCO_OT_fmanagers Credentials okay.
2017-06-22 09:10:30,358     INFO blender_cloud.flamenco.FLAMENCO_OT_fmanagers Going to fetch managers for user 59478a892487bb082c99b394
2017-06-22 09:10:30,514     INFO blender_cloud.flamenco.FLAMENCO_OT_fmanagers Signalling that we want to cancel anything that's running.

foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 
foo@rendernavi2 /mnt/backups/blender/rfb/rfb_alpha $ 2017-06-22 09:11:12,016     INFO blender_cloud.flamenco.FLAMENCO_OT_render Starting
2017-06-22 09:11:12,019     INFO blender_cloud.flamenco.FLAMENCO_OT_render Checking credentials
2017-06-22 09:11:12,159     INFO blender_cloud.flamenco.FLAMENCO_OT_render Credentials okay.
2017-06-22 09:11:12,159     INFO blender_cloud.flamenco.FLAMENCO_OT_render Saving copy to temporary file /home/foo/dl/blender/speed_testing/portals2.flamenco.blend
2017-06-22 09:11:12,174     INFO blender_cloud.flamenco.FLAMENCO_OT_render Will output render files to /tmp/output/speed_testing/portals2/######
2017-06-22 09:11:12,176     INFO blender_cloud.flamenco.bam_interface Executing /opt/blender-2.78-19791760880-linux-glibc219-x86_64/2.78/python/bin/python3.5m -m bam.pack --input /home/foo/dl/blender/speed_testing/portals2.flamenco.blend --output /tmp/storage/2017-06-22-091112.175099-shaunmiller1024-portals2.flamenco/portals2.flamenco.blend --mode FILE
2017-06-22 09:11:12,177     INFO io_blend_utils.pythonpath Using wheel /opt/blender-2.78-19791760880-linux-glibc219-x86_64/2.78/scripts/addons/io_blend_utils/blender_bam-unpacked.whl to run BAM-Pack
2017-06-22 09:11:12,312     INFO blender_cloud.flamenco.bam_interface   
2017-06-22 09:11:12,313     INFO blender_cloud.flamenco.bam_interface   scanning deps: b'/home/foo/dl/blender/speed_testing/portals2.flamenco.blend'...
2017-06-22 09:11:12,357     INFO blender_cloud.flamenco.bam_interface     blend:       b'/home/foo/dl/blender/speed_testing/portals2.flamenco.blend'
2017-06-22 09:11:12,535     INFO blender_cloud.flamenco.bam_interface   
2017-06-22 09:11:12,536     INFO blender_cloud.flamenco.bam_interface   archiving: 4 files
2017-06-22 09:11:12,536     INFO blender_cloud.flamenco.bam_interface     copying: b'/home/foo/dl/blender/speed_testing/wood_texture.jpg' -> b'/tmp/storage/2017-06-22-091112.175099-shaunmiller1024-portals2.flamenco/wood_texture.jpg'
2017-06-22 09:11:12,536     INFO blender_cloud.flamenco.bam_interface     copying: b'/home/foo/dl/blender/speed_testing/silent_hill_symbol.png' -> b'/tmp/storage/2017-06-22-091112.175099-shaunmiller1024-portals2.flamenco/silent_hill_symbol.png'
2017-06-22 09:11:12,537     INFO blender_cloud.flamenco.bam_interface     copying: b'/home/foo/dl/blender/speed_testing/knights_of_eastern_calculus.jpg' -> b'/tmp/storage/2017-06-22-091112.175099-shaunmiller1024-portals2.flamenco/knights_of_eastern_calculus.jpg'
2017-06-22 09:11:12,537     INFO blender_cloud.flamenco.bam_interface     written: b'/tmp/storage/2017-06-22-091112.175099-shaunmiller1024-portals2.flamenco/portals2.flamenco.blend'
2017-06-22 09:11:12,546     INFO blender_cloud.flamenco.bam_interface The process stopped with status code 0
2017-06-22 09:11:12,546     INFO blender_cloud.flamenco.FLAMENCO_OT_render Going to fetch manager 59478a892487bb082c99b394
SORTING PATH REPLACEMENTS
2017-06-22 09:11:12,676     INFO blender_cloud.flamenco Going to create Flamenco job:
{
    "job_type": "blender-render",
    "manager": "594880cd2487bb0998cf03cf",
    "name": "Render portals2.flamenco.blend",
    "priority": 50,
    "project": "5948809a2487bb0998cf03ca",
    "settings": {
        "blender_cmd": "{blender}",
        "chunk_size": 1,
        "filepath": "/tmp/storage/2017-06-22-091112.175099-shaunmiller1024-portals2.flamenco/portals2.flamenco.blend",
        "frames": "",
        "render_output": "/tmp/output/speed_testing/portals2/######"
    },
    "status": "queued",
    "user": "59478a892487bb082c99b394"
}
2017-06-22 09:11:12,694     INFO pillarsdk.api Pillar-Request-Id: 43b92739-64fc-4d4f-bc65-3ebc77e08464
2017-06-22 09:11:12,863     INFO pillarsdk.api Response[403]: FORBIDDEN
2017-06-22 09:11:12,864     INFO blender_cloud.flamenco.FLAMENCO_OT_render Signalling that we want to cancel anything that's running.
Error: Error creating Flamenco job: Failed. Response status: 403. Response message: FORBIDDEN. Request URL: https://cloud.blender.org/api/flamenco/jobs. Error message: {"_status": "ERR", "_code": 403, "_message": "You don't have the permission to access the requested resource. It is either read-protected or not readable by the server."}

```

**Comment by sybrenstuvel** [comment]
> Mongodb version: 1:2.4.9-1ubuntu2

The Manager [requires MongoDB 3.2 or newer](https://www.flamenco.io/docs/user_manual/installation/#manager-installation-and-configuration).

The 403 is on our side, there's something still missing in the server code. I'll get on it right now.

**Comment by sybrenstuvel** [comment]
I've fixed the issue in Flamenco Server, you should be able to create new Flamenco jobs now.

**Comment by binarypearl** [comment]
Great, thanks!  I'll try it out tonight.  I'll also get MongoDB from their website instead of the ubuntu/mint archives.

--Shaun

**Comment by binarypearl** [comment]
And that worked!  I was able to submit a job.  But now I broke it :)  Will close this and create a new issue.

--Shaun
