### ISSUE TITLE
Starting a Job in Windows leads to Python crash

### ISSUE THREAD

**Issue by stevygee** [armadillica/flamenco#207]
Using latest stable Blender (2.78c) with Blender Cloud Add-on 1.7.2 on Windows 10 64-bit:
- Configured Blender Cloud Add-on, selected Manager and Project
- Using default scene
- Storage and Output set to local directories for now
- Saved scene in Project directory
- Frame Range 1-1
- Hit "Render on Flamenco"
- I get "Flamenco is packing your files + dependencies" and after a few seconds, "Python has stopped working"

Command prompt output is:
```
Unable to execute BAM pack
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blender_cloud\flamenco\__init__.py", line 341, in bam_pack
    missing_sources = await bam_interface.bam_copy(filepath, outfile, exclusion_filter)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blender_cloud\flamenco\bam_interface.py", line 122, in bam_copy
    raise CommandExecutionError('Process stopped with status %i' % proc.returncode)
blender_cloud.flamenco.bam_interface.CommandExecutionError: Process stopped with status 3221226505
Error: Unable to execute BAM pack: Process stopped with status 3221226505
```

I already setup a Manager on a Raspberry Pi. My workers as well as the client are all Windows machines. Hope we can figure this out 😸 

I also tried to send a job with a nightly build of Blender yesterday, and I also get a Python crash.

**Comment by stevygee** [comment]
I just realized this is actually a issue concerning the Blender Cloud Add-on, so I reported it at [developer.blender.org](https://developer.blender.org/T52161) instead!
