### ISSUE TITLE
Worker - Can't find project file - windows 10

### ISSUE THREAD

**Issue by tcheng00** [armadillica/flamenco#216]
Hi, 

I'm getting an error after setting up the Manager and worker.   Here is the log error message:

```
**2018-01-17T23:31:20.532411+00:00: > Error: Cannot read file 'P:\_system\flamenco\flamenco-worker-2.1.0-windows\/Projects/_temp/2018-01-17-182938.425657-thomascheng-ast_rig_LibertyPrimeAni_v001_tch.flamenco/ast_rig_LibertyPrimeAni_v001_tch.flamenco.blend': No such file or directory**

2018-01-17T23:31:20.541147+00:00: > Traceback (most recent call last):

2018-01-17T23:31:20.541649+00:00: > File "P:\_system\blender\app\stable\2.79\scripts\modules\addon_utils.py", line 350, in enable

2018-01-17T23:31:20.541649+00:00: > mod.register()

2018-01-17T23:31:20.542150+00:00: > File "P:\_system\blender\app\stable\2.79\scripts\addons\object_boolean_tools.py", line 1455, in register

2018-01-17T23:31:20.542150+00:00: > km = wm.keyconfigs.addon.keymaps.new(name='Object Mode')

2018-01-17T23:31:20.542150+00:00: > AttributeError: 'NoneType' object has no attribute 'keymaps'

2018-01-17T23:31:20.542652+00:00: > Traceback (most recent call last):

2018-01-17T23:31:20.542652+00:00: > File "P:\_system\blender\app\stable\2.79\scripts\modules\addon_utils.py", line 350, in enable

2018-01-17T23:31:20.542652+00:00: > mod.register()

2018-01-17T23:31:20.543152+00:00: > File "P:\_system\blender\addons\HOps\__init__.py", line 42, in register

2018-01-17T23:31:20.543152+00:00: > register_all()

2018-01-17T23:31:20.543152+00:00: > File "P:\_system\blender\addons\HOps\registration.py", line 23, in register_all

2018-01-17T23:31:20.543654+00:00: > register_keymap()

2018-01-17T23:31:20.543654+00:00: > File "P:\_system\blender\addons\HOps\keymap.py", line 14, in register_keymap

2018-01-17T23:31:20.543654+00:00: > km = kc.keymaps.new(name="3D View", space_type="VIEW_3D")

2018-01-17T23:31:20.544156+00:00: > AttributeError: 'NoneType' object has no attribute 'keymaps'

2018-01-17T23:31:20.545659+00:00: > Exception in module register(): 'P:\\_system\\blender\\app\\stable\\2.79\\scripts\\addons\\object_boolean_tools.py'

2018-01-17T23:31:20.546161+00:00: > Exception in module register(): 'P:\\_system\\blender\\addons\\HOps\\__init__.py'

2018-01-17T23:31:20.546161+00:00: > No addon key configuration space found, so no custom hotkeys added.

2018-01-17T23:31:20.671003+00:00: >

2018-01-17T23:31:20.671504+00:00: > Blender quit

2018-01-17T23:31:20.737089+00:00: blender_render.(task_id=5a5fdc783bea6a423ddde17e, command_idx=0): Error executing: Command failed with status 1

2018-01-17T18:34:53-0500: Manager assigned task 5a5fdc783bea6a423ddde17e to worker 192.168.1.247 (abhome01)

2018-01-17T23:34:56.152481+00:00: blender_render.(task_id=5a5fdc783bea6a423ddde17e, command_idx=0): Error in settings: filepath '/Projects/_temp/2018-01-17-182938.425657-thomascheng-ast_rig_LibertyPrimeAni_v001_tch.flamenco/ast_rig_LibertyPrimeAni_v001_tch.flamenco.blend' does not exist

2018-01-17T18:36:29-0500: Manager assigned task 5a5fdc783bea6a423ddde17e to worker 192.168.1.247 (abhome01)

2018-01-17T23:36:31.911584+00:00: blender_render.(task_id=5a5fdc783bea6a423ddde17e, command_idx=0): Error in settings: filepath '/Projects/_temp/2018-01-17-182938.425657-thomascheng-ast_rig_LibertyPrimeAni_v001_tch.flamenco/ast_rig_LibertyPrimeAni_v001_tch.flamenco.blend' does not exist
```

It looks like the path has the worker directory added to the beginning, which looks incorrect.  The path should look like:

`P:\Projects\_temp\2018-01-17-182938.425657-thomascheng-ast_rig_LibertyPrimeAni_v001_tch.flamenco`

Please let me know what I can do.  Thanks.

**Comment by sybrenstuvel** [comment]
If that doesn't solve the problem, let me know the version of the Workers and Manager you're using, and your `flamenco-manager.yaml` file.

**Comment by sybrenstuvel** [comment]
> Use absolute paths and forward slashes. `P:` is a relative path, whereas `P:/` is an absolute path.

Now that I've properly formatted your issue (using triple-backticks "```") I see that you're already using absolute paths. Still, try using [forward slashes only](https://www.flamenco.io/docs/user_manual/installation/).

**Comment by tcheng00** [comment]
Ok, I'll give this a try tomorrow.  I got the log from flamenco render task on the blender cloud after it failed.  I'm using blender 2.79 official, blender cloud addon 1.8, flamenco 2.1.0, and windows 10 pro with latest updates.

**Comment by tcheng00** [comment]
I just try to reinstall everything and linking my manager to the blender cloud project.  Manager seems to be working, but Worker is giving me sign-on errors.  I've copy and pasted the text from the console windows of both manager and worker.  I've also attached the flamenco-manager.yaml file.   I'm able to reach the manager fine from 192.168.1.166:8083, but worker can't seem to find it.  It's strange because I didn't have a problem getting worker to connect the first time I tried. 

[flamenco.zip](https://github.com/armadillica/flamenco/files/1645288/flamenco.zip)

**Comment by sybrenstuvel** [comment]
Deleting stuff and trying again is generally not the way to solve problems; figuring out what is going wrong is a better approach.

> I'm able to reach the manager fine from 192.168.1.166:8083, but worker can't seem to find it.

According to the worker log, it can find it just fine. It just gets a '401 Unauthorized' response from the Manager.

By reinstalling everything I guess you also threw away the MongoDB database contents. This also deletes the worker registration from the Manager; once the worker tries to reconnect using its old username/password, of course that'll fail. Run the worker with `--reregister` to make it forget its credentials and try again.

>  I've also attached the flamenco-manager.yaml file.

You forgot to take out your `manager_secret` key, so now the entire world has access to your manager. I **strongly** suggest you re-link your manager to obtain a new secret.

**Comment by tcheng00** [comment]
Thanks for pointing that out.  I reregister the worker and it is connecting again.   I also reauthenticated the token link for the manager and reselected the project for the manager.   Everything is back to the way it was before.   I checked .yaml file and made sure the blender path and render path have absolute paths with forward slashes.  Then I sent a job to the manager.  It throws back a path error and I've attached a screen capture of what I see.
![error-msg](https://user-images.githubusercontent.com/5704055/35153584-1fa236cc-fcf5-11e7-80ba-481fc6c06531.jpg)

**Comment by sybrenstuvel** [comment]
You haven't defined the `job_storage` path replacement variable yet, so that could be a cause.
The screenshot breaks off the line from the log, so please just copy-paste it here instead of screenshotting. Also when you screenshot you pretty much force me to type out everything I want to visit (like the job & task IDs) instead of simply allowing me to copy-paste the information.

> I only have basic IT knowledge

That's fine. Just know that everything we log we do for a reason, so it's important to be able to read what's there, and make sure that I have the information needed to help you out.

**Comment by tcheng00** [comment]
Thanks for the help.  Ok, I copied and paste the entire log below:

```
2018-01-19T08:20:56-0500: Manager assigned task 5a61f0ae3bea6a547af3f401 to worker 192.168.1.247 (abhome01)

2018-01-19T13:21:01.974828+00:00: blender_render.(task_id=5a61f0ae3bea6a547af3f401, command_idx=0): Error in settings: filepath '/Projects/_temp/2018-01-19-082028.871811-thomascheng-ast_rig_LibertyPrimeAni_v001_tch.flamenco/ast_rig_LibertyPrimeAni_v001_tch.flamenco.blend' does not exist
```

> You haven't defined the job_storage path replacement variable yet, so that could be a cause.

I defined the **Job File Path** and **Job Output Path** in the Blender Cloud addon 1.8.  I used the following path for both.  

**P:/Projects/_temp/**

Should I put that path directly into the flamenco-manager.yaml instead?  Basically replacing **{job_storage}** and **{render}**

**Comment by tcheng00** [comment]
I went ahead and replaced **{job_storage}** and **{render}** directly with **P:/Projects/_temp/** , but it is giving me the same error.

**Comment by sybrenstuvel** [comment]
You have to define those variables in the `path_replacement` section in `flamenco-manager.yaml`.

Please configure the Manager and Worker to log at debug level, so that we have more detail about what's going on. Start the Manager with `flamenco-manager -debug` to do this. For the worker, edit `flamenco-worker.cfg` and set `level=DEBUG` in the `[logger_flamenco_worker]` section.

**Comment by sybrenstuvel** [comment]
Closing due to inactivity.
