### ISSUE TITLE
NameError: name 'replacements' is not defined

### ISSUE THREAD

**Issue by binarypearl** [armadillica/flamenco#231]
I'm trying to fire up Flamenco again after several months.  I'm using the same OS install as before on Ubuntu 18.04, but I upgraded the following components:

Blender 2.79.6 (beta) -> 2.79.7 (beta)
Flamenco Manager 2.3 -> 2.4.3
Flamenco Worker 2.2 -> 2.3.1
Blender cloud addon 1.11.1  -> 1.13.2 

One thing I did, is I copied the worker's flamenco-worker.cfg and the managers flamenco-manager.yaml file from the previous versions into the current versions (noting in case that was a bad idea)

I think I have everything configured correctly but once I click on 'Render on Flamenco' button in Blender, I get the following stack trace below (it's a lot of output).

Do you know what I might be doing wrong?  Thanks!

--Shaun

smiller@ankinavi:~/Downloads/blender-2.79.7.exp$ Exception while running task: name 'replacements' is not defined
Exception from asynchronous task
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  [Previous line repeated 3 more times]
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  [Previous line repeated 1 more times]
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  [Previous line repeated 2 more times]
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  [Previous line repeated 6 more times]
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  [Previous line repeated 7 more times]
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  [Previous line repeated 5 more times]
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  [Previous line repeated 8 more times]
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  [Previous line repeated 4 more times]
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at /home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py:255> exception=NameError("name 'replacements' is not defined")>: resulted in exception
Traceback (most recent call last):
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 95, in kick_async_loop
    res = task.result()
  [Previous line repeated 10 more times]
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "/home/smiller/.config/blender/2.79/scripts/addons/blender_cloud/flamenco/sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined

**Comment by jaguardigital** [comment]
I'm getting the same error. 

Blender: 2.79b (on windows 10)
Flamenco Manager: 2.4.3 (installed on Ubuntu 18.03)
Flamenco Worker: 2.3.1 (on windows 10 64 bits)

When sending the job by pressing the "Flamenco render" button on the render tab of blender shows this message (repeatedly) at the blender console:

Starting
Checking credentials
Credentials okay.
Saving copy to temporary file E:\calamar\PRODUCCION\3_ILUMINACION\xx flamenco.flamenco.blend
MeasureIt: Cleaning data
Info: All Groups exported.
Will output render files to E:\calamar\RENDER\######
Going to fetch manager 5a4f951dda929216b8ea2c1e
Exception while running task: name 'replacements' is not defined
Signalling that we want to cancel anything that's running.
Exception from asynchronous task
Traceback (most recent call last):
  File "C:\Users\JAGUAR\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blender_cloud\async_loop.py", line 280, in _stop_async_task
    self.async_task.result()  # This re-raises any exception of the task.
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\JAGUAR\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blender_cloud\flamenco\__init__.py", line 305, in async_execute
    'render_output': manager.replace_path(render_output),
  File "C:\Users\JAGUAR\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blender_cloud\flamenco\sdk.py", line 80, in replace_path
    for varname, path in replacements:
NameError: name 'replacements' is not defined
<Task finished coro=<FLAMENCO_OT_render.async_execute() done, defined at C:\Users\JAGUAR\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blender_cloud\flamenco\__init__.py:255> exception=NameError("name 'replacements' is not defined",)>: resulted in exception
....

This is the content of the flamenco-manager.yaml file on the flamenco-manager folder:

# Configuration file for Flamenco Manager.
# For an explanation of the fields, refer to flamenco-manager-example.yaml
# NOTE: this file will be overwritten by Flamenco Manager's web-based configuration system.
# This file was written on 2019-05-19 18:10:45 -05:00
mode: production
manager_name: Flamenco Manager
database_url: ""
database_path: ./db
task_logs_path: ./task-logs
listen: :8083
own_url: http://192.168.0.222:8083/
flamenco: https://cloud.blender.org/
manager_id: 5ce1918ac0e4872a76b6ae79
manager_secret: SRVQ8rhTCjkAUY53yh0yogDAqzIGEb9ABOJB6aJcItR6JA
tlskey: ""
tlscert: ""
download_task_sleep: 10m0s
download_task_recheck_throttle: 10s
variables:
  blender:
    darwin: /Volume/Applications/Blender/blender
    linux: /home/loop/Descargas/blender-2.79b-linux-glibc219-x86_64/blender
    windows: "C:/Program Files/Blender Foundation/Blender/blender.exe"
  ffmpeg:
    darwin: /Volume/Applications/FFmpeg/ffmpeg
    linux: /usr/bin/ffmpeg
    windows: "C:/Program Files/ffmpeg/bin/ffmpeg.exe"
path_replacement:
  job_storage:
    darwin: /Volume/shared/flamenco-jobs
    linux: "/mnt/RAID-LOOP/GWS Expovinos/Calamar/render/flamenco-jobs"
  render:
    darwin: /Volume/render
    linux: "/mnt/RAID-LOOP/GWS Expovinos/Calamar/render"
    windows: R:/calamar/RENDER
task_update_push_max_interval: 5s
task_update_push_max_count: 3000
cancel_task_fetch_max_interval: 10s
active_task_timeout_interval: 10m0s
active_worker_timeout_interval: 1m0s
task_cleanup_max_age: 336h0m0s
worker_cleanup_max_age: 0s
worker_cleanup_status:
- offline
blacklist_threshold: 3
task_fail_after_softfail_count: 3
watch_for_latest_image: ""
ssdp_discovery: true
ssdp_device_uuid: 7401c189-ef69-434b-b4d8-56d00075faf5
test_tasks:
  test_blender_render:
    job_storage: '{job_storage}/test-jobs'
    render_output: '{render}/test-renders'
shaman:
  fileStorePath: ../shaman-file-store
  checkoutPath: ../shaman-checkout
  garbageCollect:
    period: 0s
    maxAge: 744h0m0s
    extraCheckoutPaths: []
user_authentication:
  disableSecurity: false
  publicKeysDownloadInterval: 1h0m0s
worker_registration_secret: ""

**Comment by jaguardigital** [comment]
Just in case, I got the same error on blender 2.8 console.

**Comment by sybrenstuvel** [comment]
Thanks for the report. I fixed it in the just-released [version 1.13.3](https://cloud.blender.org/services).

**Comment by binarypearl** [comment]
The update worked for me, thank you!

**Comment by jaguardigital** [comment]
ok it also worked here, thanks :)
