### ISSUE TITLE
cli client 403 error

### ISSUE THREAD

**Issue by mormotion** [armadillica/flamenco#233]
When attempting to use the cli client, I get the following error.  Given the time since the client has last been updated, has something changed about the way the server authenticates the user?

> 
> python3 blender_render.py -u https://cloud.blender.org/ /mnt/flamenco/test/bmw27_cpu.blend 1
> Reading credentials from /home/ubuntu/.config/blender/2.81/config/blender_id/profiles.json
> Logging in as morrisonmotion@gmail.com
> =============== User info ===============
> Traceback (most recent call last):
>   File "blender_render.py", line 353, in <module>
>     main()
>   File "blender_render.py", line 268, in main
>     create_render_job(args.server_url, args.token, settings, args)
>   File "blender_render.py", line 143, in create_render_job
>     user_id = find_user_id(server_url, auth_token)
>   File "blender_render.py", line 61, in find_user_id
>     resp.raise_for_status()
>   File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://cloud.blender.org/api/users/me
>

**Comment by sybrenstuvel** [comment]
The CLI client should work in theory. Have you verified your Blender ID credentials from within Blender 2.81?

**Comment by sybrenstuvel** [comment]
Closing issue due to inactivity.
