### ISSUE TITLE
Blender Path and Settings Path on Manager

### ISSUE THREAD

**Issue by fsiddi** [armadillica/flamenco#59]
Currently we store them as config values, but in the future if would be good to store them in the manager database. This way it will be possible to have an API to to set them remotely from the server.

Of course if the manager is "private", it won't be possible to change those settings. This could be achieved by adding a PRIVATE_SETTINGS=True config value (by default the value will be False).

**Comment by peppelinux** [comment]
Using stable realse I get:

(Flamenco.io)wert@goose:~/Progs/Flamenco.io/flamenco/flamenco/manager$ python manage.py runserverINFO:alembic.migration:Context impl SQLiteImpl.
INFO:alembic.migration:Will assume non-transactional DDL.
Please enter the shared blender path for the simple_blender_render command
Linux path: /home/wert/Progs/Flamenco.io/blender-2.75a-linux-glibc211-x86_64/blender 
OSX path: 
Windows path: 
Traceback (most recent call last):
  File "manage.py", line 113, in <module>
    manager.run()
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 73, in runserver
    value=json.dumps(configuration))
  File "<string>", line 4, in __init__
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 269, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 525, in _declarative_constructor
    (k, cls_.__name__))
TypeError: <flask_script.commands.Command object at 0x2ac13d0>: 'value' is an invalid keyword argument for JobType

Is my mistake ?
Have I understood how to set them ?

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
