### ISSUE TITLE
Workers can be registered in more than one Manager at the same time

### ISSUE THREAD

**Issue by Eibriel** [armadillica/flamenco#99]
Workers can be registered in more than one Manager at the same time!
The workers accepts commands from any IP/Manager

**Comment by aditiapratama** [comment]
I've run server, dashboard and manager in master, and then I only run worker in the node, is this setup works like that? Or in every node I should run both manager and worker?

If I run only worker in node, I got following error
```
[root@dom01 worker]# python2.7 manage.py runserver
 * Running on http://0.0.0.0:5000/
 * Restarting with reloader
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/farm/brender2/brender/worker/application/controllers.py", line 65, in register_worker
    requests.get(manager_url)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='192.168.1.254', port=7777): Max retries exceeded with url: /info (Caused by <class 'socket.error'>: [Errno 110] Connection timed out)
```

If I run worker from master, then there's no error happening.

**Comment by Eibriel** [comment]
Hi Aditia, that error means that the Worker don't find the Manager on 192.168.1.254:7777
The setup is correct!, Only the workers run in the nodes
